---
apiVersion: v1
kind: Secret
metadata:
  name: "docker-credentials-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "manager.name" . }}
    chart: {{ include "manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "manager.dockerconfig" . }}
