{{- if .Values.global.registry.internal -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "docker-registry.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "docker-registry.fullname" . }}
    chart: {{ include "docker-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "docker-registry.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "docker-registry.fullname" . }}
        release: {{ .Release.Name }}
        logging: "true"
    spec:
      {{- if not .Values.global.registry.insecure }}
      initContainers:
        - name: "htpasswd-{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/entrypoint.sh
          args:
            - htpasswd
            - -Bbn
            - "{{ .Values.global.registry.username }}"
            - "{{ .Values.global.registry.password }}"
          volumeMounts:
            - name: "configmap-{{ .Chart.Name }}"
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - name: "auth-{{ .Chart.Name }}"
              mountPath: /auth
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            {{- if not .Values.global.registry.insecure }}
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            - name: REGISTRY_HTTP_SECRET
              value: "{{ .Values.global.registry.password }}" 
            {{- end }}
            {{- if and .Values.global.persistence.mode (eq .Values.global.persistence.mode "s3") }}
            - name: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
              value: "false"            
            - name: REGISTRY_STORAGE
              value: s3
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              value: {{ .Values.global.persistence.accessKey }}
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              value: {{ .Values.global.persistence.secretKey }}
            - name: REGISTRY_STORAGE_S3_REGION
              value: {{ .Values.global.persistence.region }}
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: {{ .Values.global.persistence.bucket }}
            - name: REGISTRY_STORAGE_S3_ROOTDIRECTORY
              value: /{{ .Release.Name }}/
            {{- end }}
          {{- if not .Values.global.registry.insecure }}
          volumeMounts:
            - name: "auth-{{ .Chart.Name }}"
              mountPath: /auth
              readOnly: true
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.global.tolerations }}  
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
      volumes:
        - name: "configmap-{{ .Chart.Name }}"
          configMap:
            defaultMode: 0700
            name: {{ include "docker-registry.fullname" . }}
        {{- if not .Values.global.registry.insecure }}
        - name: "auth-{{ .Chart.Name }}"
          emptyDir: {}
        {{- end }}
{{- end -}}
