{{- if .Values.proxy.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ template "docker-registry-proxy.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ template "docker-registry-proxy.fullname" . }}
    kubernetes.io/cluster-service: "true"
    version: v0.4
    app: {{ include "docker-registry-proxy.fullname" . }}
    chart: {{ include "docker-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ template "docker-registry-proxy.fullname" . }}
      kubernetes.io/cluster-service: "true"
      version: v0.4
  template:
    metadata:
      labels:
        k8s-app: {{ template "docker-registry-proxy.fullname" . }}
        kubernetes.io/cluster-service: "true"
        version: v0.4
    spec:
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: "{{ template "docker-registry.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5000
{{- end -}}
