{{- if .Values.ingress.enabled -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $dot := . }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "ui.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "ui.name" . }}"
    chart: "{{ include "ui.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ template "ui.fullname" $dot }}
              servicePort: http
  {{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "ui.fullname" . }}-grpc"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "ui.name" . }}"
    chart: "{{ include "ui.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: "/tensorflow.serving."
            backend:
              serviceName: {{ template "ui.fullname" $dot }}
              servicePort: grpc
          - path: "/timemachine."
            backend:
              serviceName: {{ template "ui.fullname" $dot }}
              servicePort: grpc
          - path: "/hydrosphere."
            backend:
              serviceName: {{ template "ui.fullname" $dot }}
              servicePort: grpc
  {{- end }}
{{- end }}
