# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
public: true
sonar:
  enabled: false

global:
  ingress:
    frontendUrl: ui.hydrosphere.io #Domain name to frontend
    issuer: letsencrypt-prod #Cert-manager issuer name
    path: "/"
    enableGrpc: true

  tolerations: []
  
image:
  full:  hydrosphere/serving-manager-ui:2.4.0
  pullPolicy:  IfNotPresent

service:
  type: ClusterIP
  httpPort: 9090
  grpcPort: 9091

ingress:
  enabled: false

configuration: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
