dependencies:
   - name: docker-registry
     repository: file://../docker-registry
     version: 0.1.0
     condition: global.dockerRegistry.enabled
   - name: postgresql
     repository: file://../postgres
     version: 7.7.1
     condition: global.postgres.enabled
   - name: gateway
     repository: file://../gateway
     version: 0.1.0
   - name: manager
     repository: file://../manager
     version: 0.1.0
   - name: ui
     repository: file://../ui
     version: 0.1.0
