global:
  shadowing_on: true
  frontend_url: "http://hydro-serving.local"
  alerting_on: false
  reqstore_enabled: false  
  persistence:
    enabled: false
  dockerRegistry:
    enabled: true
    host: ""
    username: "example"
    password: "example"

  hydrosphere:
    docker:
      host: ""
      username: ""
      password: ""

postgresql:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 9.6
    pullPolicy: IfNotPresent   

  postgresqlUsername: postgres
  postgresqlPassword: hydr0s3rving
  postgresqlDatabase: hydro-serving     

mongodb:
  enabled: true
  image:
    repository: bitnami/mongodb
    tag: 4.0.13-debian-9-r22
    pullPolicy: IfNotPresent

  usePassword: true
  mongodbRootPassword: hydr0s3rving
  mongodbUsername: root
  mongodbPassword: hydr0s3rving
  mongodbAuthDatabase: admin
  mongodbDatabase: hydro-serving-data-profiler

ui:
  public: true  
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - hydro-serving.local
    path: "/"
    tls: []
    #  - hosts:
    #    - hydro-serving.local
    #    secretName: qa-hydro-tls

manager:
  postgres:
    postgresqlUsername: postgres
    postgresqlPassword: hydr0s3rving
    postgresqlDatabase: hydro-serving
  
docker-registry:
  proxy:
    enabled: true
  ingress:
    enabled: false